### ISSUE TITLE
Authentic mini-map in game

### ISSUE THREAD

**Issue by KiyanSomji** [cardiffuni/Gravitational-Waves#10]
# User Story
``` As a user I'd like to see the map in the game that greatly resembles the environment in a gravitational wave observatory ```

## Acceptance Criteria
- [ ] Assets used for game map resemble the environment of the ones in an observatory.

**Comment by Somafet** [comment]
Tutorial by Brackeys for this:

[The video](https://www.youtube.com/watch?v=28JTTXqMvOU)
