### ISSUE TITLE
Network Intergration

### ISSUE THREAD

**Issue by Somafet** [cardiffuni/Gravitational-Waves#43]
# User Story
``` As a user, I want to be able to move around the environment, see others move and interact with the environment and have the camera follow me so that I navigate around the game and be immersed with other players.```

## Acceptance Criteria
- [x] The user must be able to always see their character when in-game.
- [x] The user must be able to see where they are even when fully or partially obscured.
- [x] The user must be able to see where others are within the camera view even when fully or partially obscured.
- [x] The user must have their movements and actions seen by other users
- [x] The user must be able to see others and their movements and actions 
## Non-Functional Criteria
- Following camera movement must be introduced.
- The camera must always focus on the player's character.
- Slight smooth delay is permitted if it looks visually pleasing.

**Comment by TeaWithLucas** [comment]
Isn't this addressed by #30
